# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Haining's
tagline:          'Soft thoughts for programmers'
description:      Programming Blog
url:              https://carahainingwang.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

plugins: [jekyll-paginate]
paginate:         5


# Custom vars
version:          1.0.0
params:
  disqusShortname: "spf13"


github: [metadata]
repo: https://github.com/carahainingwang
