timezone: America/Los_Angeles

# Dependencies
markdown: kramdown
highligher: rouge
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:
tagline:          Bruce Eckel's Programming Blog
url:              http://carahainingwang.github.io/
baseurl:          /

# About/contact
author:
  name:           Cara Wang
  email:          whnzinc@gmail.com

theme: jekyll-theme-cayman