# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Haining's
tagline:          'Soft thoughts for programmers'
description:      Programming Blog
url:              https://carahainingwang.github.io
baseurl:          https://carahainingwang.github.io/

author:
  name:           'Haining Wang'
  url:            https://twitter.com/TechZinc
  github_username: carahainingwang

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

paginate:         5


# Custom vars
version:          1.0.0
params:
  disqusShortname: "haining"


github: [metadata]
